In [3]:
import numpy as np

### Array

In [2]:
lista = [1, 2, 3, 4]

In [3]:
lista

[1, 2, 3, 4]

In [4]:
np.array(lista)

array([1, 2, 3, 4])

##### Array de Zeros

In [28]:
np.zeros(3)

array([0., 0., 0.])

##### Array de Uns

In [30]:
np.ones(3)

array([1., 1., 1.])

### Matriz

In [18]:
matriz=[(1,2,3),(4,5,6),(7,8,9)]

In [6]:
matriz

[(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [7]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###### Matriz Zeros e Matriz Uns

In [24]:
arr = np.zeros((5,5))

In [25]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

###### Matriz identidade

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Outros Métodos

##### Sequencia Números Seguidos

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

##### Sequencia de Números igualmente espaçados

In [23]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

##### Sequencia de Números Aleatórios até um seguindo uma Distribuição Uniforme - Igual probabilidade de ser Seleccionado

In [38]:
np.random.rand(5)

array([0.43865677, 0.21914742, 0.35616795, 0.28055386, 0.06863092])

In [33]:
np.random.rand(5)*100

array([46.38303219,  8.60046424, 35.32128075,  5.81508131, 47.83936361])

In [34]:
np.random.rand(5,4)

array([[0.47134279, 0.46005085, 0.11119162, 0.53358098],
       [0.82811204, 0.67318001, 0.42721538, 0.64993089],
       [0.65331519, 0.13895013, 0.67321453, 0.68701386],
       [0.27336433, 0.11436289, 0.64990723, 0.6902329 ],
       [0.42734786, 0.16395186, 0.72408177, 0.06287478]])

##### Sequencia de Números Aleatórios seguindo uma Distribuição Normal

In [35]:
np.random.randn(5)

array([ 0.20890789, -0.80353873, -0.01913509,  0.20289485, -0.53897994])

##### Sequencia de Números Aleatórios Inteiros seguindo uma Distribuição Uniforme - Igual probabilidade de ser Seleccionado

In [37]:
np.random.randint(0, 100, 10)

array([25, 21, 80, 46, 25, 31, 87, 60, 39, 87])

In [40]:
np.round(np.random.rand(5)*100, 0)

array([84., 98., 75., 58., 92.])

###### Reshape

In [42]:
arr = np.random.rand(25)

In [43]:
arr

array([0.26189938, 0.72323329, 0.14499428, 0.29455278, 0.59461601,
       0.56449665, 0.12538266, 0.70225265, 0.4778053 , 0.53099476,
       0.52175689, 0.67327087, 0.19966413, 0.38826346, 0.87543695,
       0.75266947, 0.01728573, 0.90082216, 0.42753408, 0.30440022,
       0.1803245 , 0.97537769, 0.99973357, 0.3038192 , 0.25804283])

In [44]:
arr.reshape(5,5)

array([[0.26189938, 0.72323329, 0.14499428, 0.29455278, 0.59461601],
       [0.56449665, 0.12538266, 0.70225265, 0.4778053 , 0.53099476],
       [0.52175689, 0.67327087, 0.19966413, 0.38826346, 0.87543695],
       [0.75266947, 0.01728573, 0.90082216, 0.42753408, 0.30440022],
       [0.1803245 , 0.97537769, 0.99973357, 0.3038192 , 0.25804283]])

##### Valor Máximo e Minimo e suas Possições

In [45]:
arr.max()

0.9997335715098656

In [46]:
arr.min()

0.017285725876136082

In [47]:
arr.argmax()

22

In [48]:
arr.argmin()

16

##### Soma das Colunas e das Linhas

In [5]:
mat = np.arange(0,9).reshape(3,3)

In [6]:
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Soma Colunas

In [8]:
mat.sum(axis = 0)

array([ 9, 12, 15])

Soma Linhas

In [9]:
mat.sum(axis = 1)

array([ 3, 12, 21])