In [13]:
import numpy as np

## Indexação

In [14]:
arr = np.arange(0, 30, 3)

In [15]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [16]:
arr[3]

9

In [17]:
arr[:3]

array([0, 3, 6])

In [18]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [19]:
arr[5:9]

array([15, 18, 21, 24])

##### Alteração dos valores do Array

In [20]:
arr[2:] = 100

In [21]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

##### Indexação de Arrays de 2 dimensões

In [22]:
arr = np.arange(50).reshape(5, 10)

In [23]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [24]:
arr.shape

(5, 10)

In [25]:
arr[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [26]:
arr[3:]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [27]:
arr[2][3]

23

In [28]:
arr[:][2:]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [29]:
arr2 = arr[:3]

In [30]:
arr2[:]=100

Tambem altera o conteudo do array inicial arr

In [31]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

Para não alterar utilizar o método copy

In [32]:
arr2 = arr[:3].copy()

In [33]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

## Outra Forma de Indexação

In [34]:
arr[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [36]:
bol = arr > 50

In [37]:
arr[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [44]:
array = np.linspace(0, 60, 30)

In [45]:
array.shape

(30,)

In [46]:
array = array.reshape(3,10)

In [47]:
array

array([[ 0.        ,  2.06896552,  4.13793103,  6.20689655,  8.27586207,
        10.34482759, 12.4137931 , 14.48275862, 16.55172414, 18.62068966],
       [20.68965517, 22.75862069, 24.82758621, 26.89655172, 28.96551724,
        31.03448276, 33.10344828, 35.17241379, 37.24137931, 39.31034483],
       [41.37931034, 43.44827586, 45.51724138, 47.5862069 , 49.65517241,
        51.72413793, 53.79310345, 55.86206897, 57.93103448, 60.        ]])

In [48]:
array[:2, 2]

array([ 4.13793103, 24.82758621])

In [51]:
array[[2,1]]

array([[41.37931034, 43.44827586, 45.51724138, 47.5862069 , 49.65517241,
        51.72413793, 53.79310345, 55.86206897, 57.93103448, 60.        ],
       [20.68965517, 22.75862069, 24.82758621, 26.89655172, 28.96551724,
        31.03448276, 33.10344828, 35.17241379, 37.24137931, 39.31034483]])

In [59]:
array[[2,1],0]

array([41.37931034, 20.68965517])